
import React, { Suspense, useRef, useEffect } from 'react'
import { useGLTF, useAnimations, OrbitControls, Environment } from '@react-three/drei'
import { Canvas } from "@react-three/fiber";



function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/flying/scene.gltf')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    const obj = Object.values(actions)[0];
    obj.play();
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={11.07}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group scale={0.01}>
            <primitive object={nodes.GLTF_created_0_rootJoint} />
            <skinnedMesh
              geometry={nodes.Object_96.geometry}
              material={materials.material_0}
              skeleton={nodes.Object_96.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_99.geometry}
              material={materials.material_1}
              skeleton={nodes.Object_99.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_102.geometry}
              material={materials.material_2}
              skeleton={nodes.Object_102.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_105.geometry}
              material={materials.material_3}
              skeleton={nodes.Object_105.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_108.geometry}
              material={materials.material_4}
              skeleton={nodes.Object_108.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_111.geometry}
              material={materials.material_5}
              skeleton={nodes.Object_111.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_114.geometry}
              material={materials.material_6}
              skeleton={nodes.Object_114.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_117.geometry}
              material={materials.material_7}
              skeleton={nodes.Object_117.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_120.geometry}
              material={materials.material_8}
              skeleton={nodes.Object_120.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_123.geometry}
              material={materials.material_9}
              skeleton={nodes.Object_123.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_126.geometry}
              material={materials.material_10}
              skeleton={nodes.Object_126.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_129.geometry}
              material={materials.material_11}
              skeleton={nodes.Object_129.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_132.geometry}
              material={materials.material_12}
              skeleton={nodes.Object_132.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_135.geometry}
              material={materials.material_13}
              skeleton={nodes.Object_135.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_138.geometry}
              material={materials.material_14}
              skeleton={nodes.Object_138.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_141.geometry}
              material={materials.material_15}
              skeleton={nodes.Object_141.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_144.geometry}
              material={materials.material_16}
              skeleton={nodes.Object_144.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_147.geometry}
              material={materials.material_17}
              skeleton={nodes.Object_147.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_150.geometry}
              material={materials.material_18}
              skeleton={nodes.Object_150.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_153.geometry}
              material={materials.material_19}
              skeleton={nodes.Object_153.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_156.geometry}
              material={materials.material_20}
              skeleton={nodes.Object_156.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_159.geometry}
              material={materials.material_21}
              skeleton={nodes.Object_159.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_162.geometry}
              material={materials.material_22}
              skeleton={nodes.Object_162.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_165.geometry}
              material={materials.material_23}
              skeleton={nodes.Object_165.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_168.geometry}
              material={materials.material_24}
              skeleton={nodes.Object_168.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_171.geometry}
              material={materials.material_25}
              skeleton={nodes.Object_171.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_174.geometry}
              material={materials.material_26}
              skeleton={nodes.Object_174.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_177.geometry}
              material={materials.material_27}
              skeleton={nodes.Object_177.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_180.geometry}
              material={materials.material_28}
              skeleton={nodes.Object_180.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_183.geometry}
              material={materials.material_29}
              skeleton={nodes.Object_183.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_186.geometry}
              material={materials.material_30}
              skeleton={nodes.Object_186.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_189.geometry}
              material={materials.material_31}
              skeleton={nodes.Object_189.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_192.geometry}
              material={materials.material_32}
              skeleton={nodes.Object_192.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_195.geometry}
              material={materials.material_33}
              skeleton={nodes.Object_195.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_198.geometry}
              material={materials.material_34}
              skeleton={nodes.Object_198.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_201.geometry}
              material={materials.material_35}
              skeleton={nodes.Object_201.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_204.geometry}
              material={materials.material_36}
              skeleton={nodes.Object_204.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_207.geometry}
              material={materials.material_37}
              skeleton={nodes.Object_207.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_210.geometry}
              material={materials.material_38}
              skeleton={nodes.Object_210.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_213.geometry}
              material={materials.material_39}
              skeleton={nodes.Object_213.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_216.geometry}
              material={materials.material_40}
              skeleton={nodes.Object_216.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_219.geometry}
              material={materials.material_41}
              skeleton={nodes.Object_219.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_222.geometry}
              material={materials.material_42}
              skeleton={nodes.Object_222.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_225.geometry}
              material={materials.material_43}
              skeleton={nodes.Object_225.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_228.geometry}
              material={materials.material_44}
              skeleton={nodes.Object_228.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_231.geometry}
              material={materials.material_45}
              skeleton={nodes.Object_231.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_234.geometry}
              material={materials.material_46}
              skeleton={nodes.Object_234.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_237.geometry}
              material={materials.material_47}
              skeleton={nodes.Object_237.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_240.geometry}
              material={materials.material_48}
              skeleton={nodes.Object_240.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_243.geometry}
              material={materials.material_49}
              skeleton={nodes.Object_243.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_246.geometry}
              material={materials.material_50}
              skeleton={nodes.Object_246.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_249.geometry}
              material={materials.material_51}
              skeleton={nodes.Object_249.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_252.geometry}
              material={materials.material_52}
              skeleton={nodes.Object_252.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_255.geometry}
              material={materials.material_53}
              skeleton={nodes.Object_255.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_258.geometry}
              material={materials.material_54}
              skeleton={nodes.Object_258.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_261.geometry}
              material={materials.material_55}
              skeleton={nodes.Object_261.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_264.geometry}
              material={materials.material_56}
              skeleton={nodes.Object_264.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_267.geometry}
              material={materials.material_57}
              skeleton={nodes.Object_267.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_270.geometry}
              material={materials.material_58}
              skeleton={nodes.Object_270.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_273.geometry}
              material={materials.material_59}
              skeleton={nodes.Object_273.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_276.geometry}
              material={materials.material_60}
              skeleton={nodes.Object_276.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_279.geometry}
              material={materials.material_61}
              skeleton={nodes.Object_279.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_282.geometry}
              material={materials.material_62}
              skeleton={nodes.Object_282.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_285.geometry}
              material={materials.material_63}
              skeleton={nodes.Object_285.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_288.geometry}
              material={materials.material_64}
              skeleton={nodes.Object_288.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_291.geometry}
              material={materials.material_65}
              skeleton={nodes.Object_291.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_294.geometry}
              material={materials.material_66}
              skeleton={nodes.Object_294.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_297.geometry}
              material={materials.material_67}
              skeleton={nodes.Object_297.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_300.geometry}
              material={materials.material_68}
              skeleton={nodes.Object_300.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_303.geometry}
              material={materials.material_69}
              skeleton={nodes.Object_303.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_306.geometry}
              material={materials.material_70}
              skeleton={nodes.Object_306.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_309.geometry}
              material={materials.material_71}
              skeleton={nodes.Object_309.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_312.geometry}
              material={materials.material_72}
              skeleton={nodes.Object_312.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_315.geometry}
              material={materials.material_73}
              skeleton={nodes.Object_315.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_318.geometry}
              material={materials.material_74}
              skeleton={nodes.Object_318.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_321.geometry}
              material={materials.material_75}
              skeleton={nodes.Object_321.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Object_324.geometry}
              material={materials.material_76}
              skeleton={nodes.Object_324.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')

const Fly = () => {
  return (
    <Suspense fallback={null}>
      <Canvas camera={{ position: [0, 0, 9], fov: 50 }}>
        <OrbitControls />
        <directionalLight intensity={0.5} />
        <pointLight position={[0, -1, 5]}/>
        <pointLight position={[0, -1, -10]}/>
        <Model position={[0, -1, 0]} />
        <Environment  files={'/old_hall_1k.hdr'} background />
      </Canvas>
    </Suspense>
  );
};

export default Fly;